apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cert-manager-operator-rhmp-test
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: cert-manager-operator-test
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: cert-manager-operator.v0.15.2