apiVersion: v1
kind: Service
metadata:
  name: mortgagers-svc
  labels:
    app: mortgagers-mortgage
spec:
  type: NodePort
  ports:
    - port: 9080
      targetPort: 9080
      protocol: TCP
  selector:
    app: mortgagers-mortgage
