apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: mortgagerc-subscription
  namespace: default
  labels:
    app: mortgagerc
  annotations:
    apps.open-cluster-management.io/github-path: mortgagerc
    apps.open-cluster-management.io/github-branch: master
spec:
  channel: mortgagerc-ch/mortgagerc-channel
  placement:
    placementRef:
      name: mortgagerc-placement
      kind: PlacementRule
      group: apps.open-cluster-management.io

