apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: nginx-app
  namespace: nginx-app-ns
spec:
  componentKinds:
    - group: app.ibm.com/v1alpha1
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - nginx-app