apiVersion: v1
kind: Service
metadata:
  name: mortgagecm-mortgage
  labels:
    app: mortgagecm-mortgage
spec:
  type: NodePort
  ports:
    - port: 9080
      targetPort: 9080
      protocol: TCP
  selector:
    app: mortgagecm-mortgage
