kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: mortgagedc-deploy
  namespace: default
  labels:
    app: mortgagedc-mortgage
spec:
  strategy:
    type: Recreate
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
  replicas: 1
  test: false
  selector:
    app: mortgagedc-mortgage
    deploymentConfig: mortgagedc-mortgage
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mortgagedc-mortgage
        deploymentConfig: mortgagedc-mortgage
    spec:
      containers:
        - name: mortgagedc-mortgage
          image: 'quay.io/fxiang1/mortgage:0.5.0'
          ports:
            - containerPort: 9080
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
