apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mortgageds-deploy
  namespace: default
  labels:
    app: mortgageds-mortgage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mortgageds-mortgage
  template:
    metadata:
      labels:
        app: mortgageds-mortgage
    spec:
      containers:
        - name: mortgageds-mortgage
          image: 'quay.io/fxiang1/mortgage:0.5.0'
          ports:
            - containerPort: 9080
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
          imagePullPolicy: Always
      terminationGracePeriodSeconds: 30
