apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: advanced-cluster-security
  namespace: stackrox
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - advanced-cluster-security

