apiVersion: apps.open-cluster-management.io/v1
kind: Deployable
metadata:
  labels:
    app: gbchn
    apps.open-cluster-management.io/channel: gbchn
    apps.open-cluster-management.io/channel-type: Namespace
    release: gbchn
  name: gbchn-redisslave
  namespace: gbchn
spec:
  template:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: gbchn-redisslave
      namespace: default
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: gbchn
          release: gbchn
          role: slave
          tier: backend
      template:
        metadata:
          labels:
            app: gbchn
            release: gbchn
            role: slave
            tier: backend
        spec:
          containers:
          - env:
            - name: GET_HOSTS_FROM
              value: dns
            image: gcr.io/google_samples/gb-redisslave:v3
            imagePullPolicy: IfNotPresent
            name: gbchn
            ports:
            - containerPort: 6379
