apiVersion: apps.open-cluster-management.io/v1
kind: Deployable
metadata:
  labels:
    app: gbchn
    release: gbchn
    apps.open-cluster-management.io/channel: gbchn
    apps.open-cluster-management.io/channel-type: Namespace
  name: gbchn-frontend
  namespace: gbchn
spec:
  template:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: gbchn-frontend
      namespace: default
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: gbchn
          release: gbchn
      template:
        metadata:
          labels:
            app: gbchn
            release: gbchn
            tier: frontend
        spec:
          containers:
          - env:
            - name: GET_HOSTS_FROM
              value: dns
            image: gcr.io/google-samples/gb-frontend:v6
            imagePullPolicy: IfNotPresent
            name: frontend
            ports:
            - containerPort: 80
