apiVersion: apps.open-cluster-management.io/v1
kind: Deployable
metadata:
  labels:
    app: gbchn
    apps.open-cluster-management.io/channel: gbchn
    apps.open-cluster-management.io/channel-type: Namespace
    release: gbchn
  name: gbchn-redismaster
  namespace: gbchn
spec:
  template:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: gbchn-redismaster
      namespace: default
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: gbchn
          release: gbchn
          role: master
          tier: backend
      template:
        metadata:
          labels:
            app: gbchn
            release: gbchn
            role: master
            tier: backend
        spec:
          containers:
          - image: gcr.io/kubernetes-e2e-test-images/redis:1.0
            imagePullPolicy: IfNotPresent
            name: redis
            ports:
            - containerPort: 6379
