apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: mortgagedc-subscription
  namespace: default
  labels:
    app: mortgagedc
  annotations:
    apps.open-cluster-management.io/github-path: mortgagedc
    apps.open-cluster-management.io/github-branch: master
spec:
  channel: mortgagedc-ch/mortgagedc-channel
  placement:
    placementRef:
      name: mortgagedc-placement
      kind: PlacementRule
      group: apps.open-cluster-management.io
