apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: mortgageds-subscription
  namespace: default
  labels:
    app: mortgageds
  annotations:
    apps.open-cluster-management.io/github-path: mortgageds
    apps.open-cluster-management.io/github-branch: master
spec:
  channel: mortgageds-ch/mortgageds-channel
  placement:
    placementRef:
      name: mortgageds-placement
      kind: PlacementRule
      group: apps.open-cluster-management.io
